-- MySQL Script generated by MySQL Workbench
-- Fri Feb 22 18:12:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `project` ;

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project` DEFAULT CHARACTER SET utf8 ;
USE `project` ;

-- -----------------------------------------------------
-- Table `project`.`Filieres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`Filieres` ;

CREATE TABLE IF NOT EXISTS `project`.`Filieres` (
  `codeF` VARCHAR(45) NOT NULL,
  `Filierescol` VARCHAR(6) NULL,
  `designation` VARCHAR(45) NULL,
  PRIMARY KEY (`codeF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`Eleves`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`Eleves` ;

CREATE TABLE IF NOT EXISTS `project`.`Eleves` (
  `codeElev` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `niveau` INT NULL,
  `dateInsc` DATETIME NULL,
  `Elevescol` VARCHAR(45) NULL,
  `anneeDiplom` DATETIME NULL,
  `code_Fil` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`codeElev`),
  INDEX `code_Fil_idx` (`code_Fil` ASC),
  CONSTRAINT `code_Fil`
    FOREIGN KEY (`code_Fil`)
    REFERENCES `project`.`Filieres` (`codeF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`Modules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`Modules` ;

CREATE TABLE IF NOT EXISTS `project`.`Modules` (
  `codeModule` VARCHAR(45) NOT NULL,
  `designation` VARCHAR(45) NULL,
  `niveau` VARCHAR(45) NULL,
  `nbr_matieres` INT NULL DEFAULT 2,
  `semestre` INT NULL DEFAULT 1,
  `code_Fil` VARCHAR(45) NULL,
  PRIMARY KEY (`codeModule`),
  INDEX `code_Fil_idx` (`code_Fil` ASC),
  CONSTRAINT `code_Fil`
    FOREIGN KEY (`code_Fil`)
    REFERENCES `project`.`Filieres` (`codeF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`Matieres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`Matieres` ;

CREATE TABLE IF NOT EXISTS `project`.`Matieres` (
  `codeMat` VARCHAR(45) NOT NULL,
  `designation` VARCHAR(45) NULL,
  `poids` FLOAT NULL,
  `codeModule` VARCHAR(45) NULL,
  PRIMARY KEY (`codeMat`),
  INDEX `codeModule_idx` (`codeModule` ASC),
  CONSTRAINT `codeModule`
    FOREIGN KEY (`codeModule`)
    REFERENCES `project`.`Modules` (`codeModule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`Notes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`Notes` ;

CREATE TABLE IF NOT EXISTS `project`.`Notes` (
  `codeElev` INT NOT NULL,
  `codeMat` VARCHAR(45) NOT NULL,
  `note` FLOAT NULL DEFAULT 0,
  PRIMARY KEY (`codeElev`, `codeMat`),
  INDEX `codeMat_idx` (`codeMat` ASC),
  CONSTRAINT `codeElev`
    FOREIGN KEY (`codeElev`)
    REFERENCES `project`.`Eleves` (`codeElev`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `codeMat`
    FOREIGN KEY (`codeMat`)
    REFERENCES `project`.`Matieres` (`codeMat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`Moyennes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`Moyennes` ;

CREATE TABLE IF NOT EXISTS `project`.`Moyennes` (
  `codeElev` INT NOT NULL,
  `codeFil` VARCHAR(45) NOT NULL,
  `niveau` INT NOT NULL,
  `moyenne_ann` FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY (`codeElev`, `codeFil`, `niveau`, `moyenne_ann`),
  INDEX `codeFil_idx` (`codeFil` ASC),
  CONSTRAINT `codeElev`
    FOREIGN KEY (`codeElev`)
    REFERENCES `project`.`Eleves` (`codeElev`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `codeFil`
    FOREIGN KEY (`codeFil`)
    REFERENCES `project`.`Filieres` (`codeF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`Absences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`Absences` ;

CREATE TABLE IF NOT EXISTS `project`.`Absences` (
  `codeElev` INT NOT NULL,
  `codeMat` VARCHAR(6) NOT NULL,
  `nbr_absences` INT NULL,
  PRIMARY KEY (`codeElev`, `codeMat`),
  INDEX `codeMat_idx` (`codeMat` ASC),
  CONSTRAINT `codeElev`
    FOREIGN KEY (`codeElev`)
    REFERENCES `project`.`Eleves` (`codeElev`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `codeMat`
    FOREIGN KEY (`codeMat`)
    REFERENCES `project`.`Matieres` (`codeMat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
